name: "Macos bug"
on: [push]
jobs:
  Macos:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        version: [13, 14]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Macos
        run: |
          brew install postgresql@${{ matrix.version }}
      - name: Run cmake
        run: mkdir build && cd build && cmake ..